import { StyleSheet } from "react-native";
import { colors } from "../constants/colors";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.bg,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 24,
    paddingTop: 16,
    paddingBottom: 16,
    backgroundColor: "#fff",
    borderBottomWidth: 1,
    borderBottomColor: "#F3F4F6",
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: colors.dark,
    fontFamily: "Georgia",
  },
  backButton: {
    padding: 8,
    marginLeft: -8,
  },
  addButton: {
    backgroundColor: colors.primary,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  addButtonText: {
    color: "#fff",
    fontWeight: "600",
    fontSize: 14,
  },
  content: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 16,
  },
  eventCard: {
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 3,
  },
  eventHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 12,
  },
  eventTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: colors.dark,
    flex: 1,
    marginRight: 12,
  },
  statusBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  statusText: {
    fontSize: 12,
    fontWeight: "600",
  },
  statusUpcoming: {
    backgroundColor: "#FEF3C7",
    color: "#D97706",
  },
  statusOngoing: {
    backgroundColor: "#D1FAE5",
    color: "#059669",
  },
  statusCompleted: {
    backgroundColor: "#E5E7EB",
    color: "#4B5563",
  },
  statusCancelled: {
    backgroundColor: "#FEE2E2",
    color: "#DC2626",
  },
  eventInfoRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
    gap: 8,
  },
  eventInfoText: {
    fontSize: 14,
    color: "#6B7280",
    flex: 1,
  },
  emptyState: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 60,
  },
  emptyStateText: {
    marginTop: 16,
    fontSize: 16,
    color: "#9CA3AF",
    fontWeight: "500",
  },
  // Form Styles
  formContainer: {
    padding: 20,
  },
  inputGroup: {
    marginBottom: 20,
  },
  label: {
    fontSize: 14,
    fontWeight: "600",
    color: colors.dark,
    marginBottom: 8,
  },
  input: {
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 15,
    color: "#1F2937",
  },
  textArea: {
    height: 100,
    textAlignVertical: "top",
  },
  submitButton: {
    backgroundColor: colors.primary,
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: "center",
    marginTop: 10,
    marginBottom: 40,
  },
  submitButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
  },
  errorText: {
    color: "#EF4444",
    fontSize: 12,
    marginTop: 4,
  },
  // Detail Styles
  detailSection: {
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 5,
    elevation: 2,
  },
  detailTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: colors.dark,
    marginBottom: 16,
  },
  descText: {
    fontSize: 15,
    lineHeight: 24,
    color: "#4B5563",
  },
  statsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    backgroundColor: colors.softMint,
    borderRadius: 12,
    padding: 16,
    marginBottom: 20,
  },
  statBox: {
    alignItems: "center",
    flex: 1,
  },
  statNum: {
    fontSize: 24,
    fontWeight: "bold",
    color: colors.darkTeal,
  },
  statLabel: {
    fontSize: 12,
    color: "#6B7280",
    marginTop: 4,
  },
  actionRow: {
    flexDirection: "row",
    gap: 12,
    marginTop: 20,
  },
  editBtn: {
    flex: 1,
    backgroundColor: "#3B82F6",
    paddingVertical: 14,
    borderRadius: 10,
    alignItems: "center",
  },
  deleteBtn: {
    flex: 1,
    backgroundColor: "#EF4444",
    paddingVertical: 14,
    borderRadius: 10,
    alignItems: "center",
  },
  btnText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 15,
  },
  registrationManageButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 5,
    elevation: 2,
  },
  registrationManageIcon: {
    width: 48,
    height: 48,
    borderRadius: 14,
    backgroundColor: colors.softMint,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 14,
  },
  registrationManageTextWrap: {
    flex: 1,
  },
  registrationManageTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: colors.dark,
    marginBottom: 4,
  },
  registrationManageSub: {
    fontSize: 12,
    color: "#6B7280",
    lineHeight: 16,
  },
  registrationListContent: {
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 40,
  },
  registrationHero: {
    backgroundColor: colors.dark,
    borderRadius: 20,
    padding: 18,
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 14,
    shadowColor: colors.dark,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 10,
    elevation: 4,
  },
  registrationHeroText: {
    flex: 1,
    paddingRight: 12,
  },
  registrationHeroTitle: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "800",
    marginBottom: 6,
  },
  registrationHeroSub: {
    color: "#D1FAE5",
    fontSize: 12,
    lineHeight: 17,
  },
  registrationHeroIcon: {
    width: 56,
    height: 56,
    borderRadius: 18,
    backgroundColor: "rgba(255,255,255,0.14)",
    alignItems: "center",
    justifyContent: "center",
  },
  registrationStatsRow: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 14,
  },
  registrationStatsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginBottom: 14,
  },
  registrationStatCard: {
    flex: 1,
    minWidth: "47%",
    backgroundColor: "#FFFFFF",
    borderRadius: 14,
    paddingVertical: 14,
    paddingHorizontal: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 5,
    elevation: 2,
  },
  registrationStatValue: {
    fontSize: 20,
    fontWeight: "800",
    color: colors.dark,
    marginBottom: 4,
  },
  registrationStatLabel: {
    fontSize: 11,
    color: "#6B7280",
    fontWeight: "600",
  },
  registrationFilters: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 14,
  },
  registrationFilterButton: {
    paddingHorizontal: 13,
    paddingVertical: 9,
    borderRadius: 999,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  registrationFilterActive: {
    backgroundColor: colors.dark,
    borderColor: colors.dark,
  },
  registrationFilterText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#6B7280",
  },
  registrationFilterTextActive: {
    color: "#FFFFFF",
  },
  registrationCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 18,
    padding: 16,
    marginBottom: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 7,
    elevation: 2,
  },
  registrationTop: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 14,
  },
  avatarCircle: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: colors.softMint,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  avatarText: {
    color: colors.dark,
    fontSize: 18,
    fontWeight: "800",
  },
  registrationUser: {
    flex: 1,
    marginRight: 10,
  },
  registrationName: {
    color: colors.dark,
    fontSize: 15,
    fontWeight: "800",
    marginBottom: 3,
  },
  registrationEmail: {
    color: "#6B7280",
    fontSize: 12,
  },
  registrationPhone: {
    color: "#4B5563",
    fontSize: 12,
    marginTop: 3,
    fontWeight: "600",
  },
  registrationBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 999,
  },
  registrationBadgeText: {
    fontSize: 11,
    fontWeight: "800",
  },
  registrationMetaGrid: {
    gap: 8,
    marginBottom: 14,
  },
  registrationMetaItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  registrationMetaText: {
    flex: 1,
    color: "#6B7280",
    fontSize: 12,
  },
  registrationInfoBlock: {
    backgroundColor: "#F9FAFB",
    borderRadius: 12,
    padding: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: "#EEF2F7",
  },
  registrationInfoLabel: {
    color: "#6B7280",
    fontSize: 11,
    fontWeight: "700",
    marginBottom: 4,
  },
  registrationInfoValue: {
    color: colors.dark,
    fontSize: 14,
    fontWeight: "800",
  },
  removeRegistrationButton: {
    marginTop: 4,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: "#FEF2F2",
    borderWidth: 1,
    borderColor: "#FECACA",
    paddingVertical: 12,
    borderRadius: 12,
  },
  removeRegistrationText: {
    color: "#B91C1C",
    fontSize: 13,
    fontWeight: "800",
  },
  registrationActions: {
    flexDirection: "row",
    gap: 8,
  },
  registrationActionButton: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 10,
    borderRadius: 10,
    backgroundColor: "#F9FAFB",
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  registrationActionActive: {
    backgroundColor: colors.softMint,
    borderColor: colors.primary,
  },
  registrationCancelActive: {
    backgroundColor: "#FEE2E2",
    borderColor: "#FCA5A5",
  },
  registrationActionText: {
    fontSize: 12,
    fontWeight: "800",
    color: "#6B7280",
  },
  registrationActionTextActive: {
    color: colors.dark,
  },
  registrationCancelTextActive: {
    color: "#B91C1C",
  },
});
