import { StyleSheet, Platform } from "react-native";

export const messageStyles = StyleSheet.create({
  // ==================== CONVERSATIONS LIST ====================
  container: {
    flex: 1,
    backgroundColor: "#F8FAF9",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingTop: Platform.OS === "web" ? 16 : 50,
    paddingBottom: 12,
    backgroundColor: "#FFFFFF",
    borderBottomWidth: 1,
    borderBottomColor: "#E8F0EE",
    elevation: 2,
    shadowColor: "#006B5C",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
  },
  headerBackButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: "#F0F7F5",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: "700",
    color: "#1A2E2A",
    flex: 1,
  },
  searchBar: {
    flexDirection: "row",
    alignItems: "center",
    margin: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#E8F0EE",
  },
  searchInput: {
    flex: 1,
    marginLeft: 8,
    fontSize: 15,
    color: "#1A2E2A",
  },
  conversationItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 14,
    backgroundColor: "#FFFFFF",
    borderBottomWidth: 1,
    borderBottomColor: "#F0F5F4",
  },
  conversationItemUnread: {
    backgroundColor: "#F0F9F7",
  },
  conversationAvatar: {
    width: 54,
    height: 54,
    borderRadius: 27,
    marginRight: 14,
  },
  conversationAvatarFallback: {
    width: 54,
    height: 54,
    borderRadius: 27,
    marginRight: 14,
    backgroundColor: "#006B5C",
    alignItems: "center",
    justifyContent: "center",
  },
  conversationAvatarFallbackText: {
    color: "#FFFFFF",
    fontSize: 20,
    fontWeight: "700",
  },
  conversationContent: {
    flex: 1,
  },
  conversationHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 4,
  },
  conversationName: {
    fontSize: 16,
    fontWeight: "600",
    color: "#1A2E2A",
    flex: 1,
  },
  conversationNameUnread: {
    fontWeight: "800",
    color: "#006B5C",
  },
  conversationTime: {
    fontSize: 12,
    color: "#94A3B8",
    marginLeft: 8,
  },
  conversationTimeUnread: {
    color: "#006B5C",
    fontWeight: "600",
  },
  conversationLastMessage: {
    fontSize: 14,
    color: "#6B7C93",
    lineHeight: 20,
  },
  conversationLastMessageUnread: {
    color: "#1A2E2A",
    fontWeight: "600",
  },
  unreadBadge: {
    minWidth: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: "#006B5C",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 6,
    marginLeft: 8,
  },
  unreadBadgeText: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "700",
  },
  emptyContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingTop: 80,
  },
  emptyText: {
    fontSize: 16,
    color: "#94A3B8",
    marginTop: 12,
  },
  emptySubText: {
    fontSize: 14,
    color: "#CBD5E1",
    marginTop: 4,
  },

  // ==================== CHAT SCREEN ====================
  chatContainer: {
    flex: 1,
    backgroundColor: "#F8FAF9",
  },
  chatHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingTop: Platform.OS === "web" ? 12 : 50,
    paddingBottom: 12,
    backgroundColor: "#FFFFFF",
    borderBottomWidth: 1,
    borderBottomColor: "#E8F0EE",
    elevation: 2,
    shadowColor: "#006B5C",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
  },
  chatHeaderBackButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#F0F7F5",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 10,
  },
  chatHeaderAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    marginRight: 10,
  },
  chatHeaderAvatarFallback: {
    width: 40,
    height: 40,
    borderRadius: 20,
    marginRight: 10,
    backgroundColor: "#006B5C",
    alignItems: "center",
    justifyContent: "center",
  },
  chatHeaderAvatarFallbackText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "700",
  },
  chatHeaderInfo: {
    flex: 1,
  },
  chatHeaderName: {
    fontSize: 17,
    fontWeight: "700",
    color: "#1A2E2A",
  },
  chatHeaderStatus: {
    fontSize: 12,
    color: "#2BC56D",
    marginTop: 1,
  },
  chatHeaderProfileButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#F0F7F5",
    alignItems: "center",
    justifyContent: "center",
  },
  messagesContainer: {
    flex: 1,
    paddingHorizontal: 12,
    paddingTop: 8,
    paddingBottom: 4,
  },
  dateSeparator: {
    alignItems: "center",
    marginVertical: 12,
  },
  dateSeparatorText: {
    fontSize: 12,
    color: "#94A3B8",
    backgroundColor: "#F0F5F4",
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
    overflow: "hidden",
  },
  messageRow: {
    flexDirection: "row",
    marginBottom: 4,
    maxWidth: "80%",
  },
  messageRowMe: {
    alignSelf: "flex-end",
    justifyContent: "flex-end",
  },
  messageRowOther: {
    alignSelf: "flex-start",
    justifyContent: "flex-start",
  },
  messageBubble: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 20,
    maxWidth: "100%",
  },
  messageBubbleMe: {
    backgroundColor: "#006B5C",
    borderBottomRightRadius: 6,
  },
  messageBubbleOther: {
    backgroundColor: "#FFFFFF",
    borderBottomLeftRadius: 6,
    borderWidth: 1,
    borderColor: "#E8F0EE",
  },
  messageText: {
    fontSize: 15,
    lineHeight: 21,
  },
  messageTextMe: {
    color: "#FFFFFF",
  },
  messageTextOther: {
    color: "#1A2E2A",
  },
  messageTime: {
    fontSize: 11,
    marginTop: 4,
  },
  messageTimeMe: {
    color: "rgba(255,255,255,0.7)",
    textAlign: "right",
  },
  messageTimeOther: {
    color: "#94A3B8",
    textAlign: "left",
  },

  // ==================== INPUT BAR ====================
  inputBar: {
    flexDirection: "row",
    alignItems: "flex-end",
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: "#FFFFFF",
    borderTopWidth: 1,
    borderTopColor: "#E8F0EE",
  },
  inputWrapper: {
    flex: 1,
    flexDirection: "row",
    alignItems: "flex-end",
    backgroundColor: "#F0F7F5",
    borderRadius: 24,
    paddingHorizontal: 16,
    paddingVertical: Platform.OS === "web" ? 10 : 8,
    minHeight: 44,
    maxHeight: 120,
  },
  textInput: {
    flex: 1,
    fontSize: 15,
    color: "#1A2E2A",
    maxHeight: 100,
    lineHeight: 20,
  },
  sendButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#006B5C",
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 8,
  },
  sendButtonDisabled: {
    backgroundColor: "#CBD5E1",
  },

  // ==================== LOADING ====================
  loadingContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F8FAF9",
  },
});
